<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CrawlPagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('crawl_pages')->delete();
        
        \DB::table('crawl_pages')->insert(array (
            0 => 
            array (
                'id' => '019ce9d3-bf79-704a-8b8f-990936363d96',
                'crawl_job_id' => '019ce9d3-bf68-7369-9b76-e0277e476aa0',
                'url' => 'https://www.caterpillar.com',
                'normalized_url' => 'https://www.caterpillar.com/',
                'status' => 'failed',
                'http_status' => 403,
                'depth' => 0,
                'title' => NULL,
                'meta_description' => NULL,
                'clean_text' => NULL,
                'content_hash' => NULL,
                'word_count' => 0,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:51:34',
                'updated_at' => '2026-03-14 00:51:42',
            ),
            1 => 
            array (
                'id' => '019ce944-bbc2-7127-a328-53a9ae9d2768',
                'crawl_job_id' => '019ce944-bbad-72d8-bf3f-d0d513a061cc',
                'url' => 'http://localhost:4300',
                'normalized_url' => 'http://localhost:4300/',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 0,
                'title' => 'SleekDummy | Home',
                'meta_description' => NULL,
                'clean_text' => 'Experience the Future of Dummy Content. A premium demonstration of modern web aesthetics. Built with speed, precision, and an obsession for visual excellence. Discover More Get in Touch Lightning Fast Powered by Vite, our dummy pages load faster than you can blink. No bloat, just performance. Premium Design Coded with attention to every pixel. Micro-animations and glassmorphism included. Modern Stack Using the latest Vanilla JS and CSS techniques to ensure long-term stability.',
                'content_hash' => 'b03b56183682684dadf644de7b01942123299b759c9646da944cad61e5462fa6',
                'word_count' => 72,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:15:21',
                'updated_at' => '2026-03-13 22:15:22',
            ),
            2 => 
            array (
                'id' => '019ce944-be1a-71cb-9f10-682c959188cb',
                'crawl_job_id' => '019ce944-bbad-72d8-bf3f-d0d513a061cc',
                'url' => 'http://localhost:4300/terms.html',
                'normalized_url' => 'http://localhost:4300/terms.html',
                'status' => 'queued',
                'http_status' => NULL,
                'depth' => 1,
                'title' => NULL,
                'meta_description' => NULL,
                'clean_text' => NULL,
                'content_hash' => NULL,
                'word_count' => 0,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:15:22',
                'updated_at' => '2026-03-13 22:15:22',
            ),
            3 => 
            array (
                'id' => '019ce944-be0a-714e-b637-5f8d9c29c419',
                'crawl_job_id' => '019ce944-bbad-72d8-bf3f-d0d513a061cc',
                'url' => 'http://localhost:4300/contact.html',
                'normalized_url' => 'http://localhost:4300/contact.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Contact',
                'meta_description' => NULL,
            'clean_text' => 'Get in Touch Have questions? Our dummy support team is waiting (to not exist). Full Name Email Address Your Message Send Message',
                'content_hash' => 'f86845f4a17a36ceaeabe7b348790259c0f83625a7c9756f66ec99e14b6db70d',
                'word_count' => 22,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:15:22',
                'updated_at' => '2026-03-13 22:15:22',
            ),
            4 => 
            array (
                'id' => '019ce944-bdfb-7297-9b63-02e9db501d4d',
                'crawl_job_id' => '019ce944-bbad-72d8-bf3f-d0d513a061cc',
                'url' => 'http://localhost:4300/about.html',
                'normalized_url' => 'http://localhost:4300/about.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | About Us',
                'meta_description' => NULL,
                'clean_text' => 'About Our Mission Beyond the filler text, we aim to provide a canvas for your imagination. SleekDummy was founded on the principle that even dummy websites deserve to look stunning. We don\'t just provide "Lorem Ipsum"; we provide an experience. Our team of artificial intelligences worked tirelessly to ensure this pinker-than-average aesthetic meets the highest standards of the modern web. Every gradient is calculated, every blur is intentional. The Vision To redefine what users expect from a placeholder project. The Value Simplicity meets sophistication in every line of code.',
                'content_hash' => '84ba0557c52cceed6a45e446622fe5ed6d7149f3fbb647d2542cef186e513e28',
                'word_count' => 89,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:15:22',
                'updated_at' => '2026-03-13 22:15:22',
            ),
            5 => 
            array (
                'id' => '019ce946-3cbf-71d3-9e8c-33ba2f808cad',
                'crawl_job_id' => '019ce946-3c88-7069-bf8c-485845c94a95',
                'url' => 'http://localhost:4400',
                'normalized_url' => 'http://localhost:4400/',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 0,
                'title' => 'SleekDummy | Home',
                'meta_description' => NULL,
                'clean_text' => 'Experience the Future of Dummy Content. A premium demonstration of modern web aesthetics. Built with speed, precision, and an obsession for visual excellence. Discover More Get in Touch Lightning Fast Powered by Vite, our dummy pages load faster than you can blink. No bloat, just performance. Premium Design Coded with attention to every pixel. Micro-animations and glassmorphism included. Modern Stack Using the latest Vanilla JS and CSS techniques to ensure long-term stability.',
                'content_hash' => 'b03b56183682684dadf644de7b01942123299b759c9646da944cad61e5462fa6',
                'word_count' => 72,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:17:00',
                'updated_at' => '2026-03-13 22:17:03',
            ),
            6 => 
            array (
                'id' => '019ce946-478c-716e-8005-2cd309ec1c64',
                'crawl_job_id' => '019ce946-3c88-7069-bf8c-485845c94a95',
                'url' => 'http://localhost:4400/terms.html',
                'normalized_url' => 'http://localhost:4400/terms.html',
                'status' => 'queued',
                'http_status' => NULL,
                'depth' => 1,
                'title' => NULL,
                'meta_description' => NULL,
                'clean_text' => NULL,
                'content_hash' => NULL,
                'word_count' => 0,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:17:03',
                'updated_at' => '2026-03-13 22:17:03',
            ),
            7 => 
            array (
                'id' => '019ce946-4770-72e5-830e-541d47f38e22',
                'crawl_job_id' => '019ce946-3c88-7069-bf8c-485845c94a95',
                'url' => 'http://localhost:4400/about.html',
                'normalized_url' => 'http://localhost:4400/about.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | About Us',
                'meta_description' => NULL,
                'clean_text' => 'About Our Mission Beyond the filler text, we aim to provide a canvas for your imagination. SleekDummy was founded on the principle that even dummy websites deserve to look stunning. We don\'t just provide "Lorem Ipsum"; we provide an experience. Our team of artificial intelligences worked tirelessly to ensure this pinker-than-average aesthetic meets the highest standards of the modern web. Every gradient is calculated, every blur is intentional. The Vision To redefine what users expect from a placeholder project. The Value Simplicity meets sophistication in every line of code.',
                'content_hash' => '84ba0557c52cceed6a45e446622fe5ed6d7149f3fbb647d2542cef186e513e28',
                'word_count' => 89,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:17:03',
                'updated_at' => '2026-03-13 22:17:03',
            ),
            8 => 
            array (
                'id' => '019ce946-477e-70f6-9dcb-4bacb5809def',
                'crawl_job_id' => '019ce946-3c88-7069-bf8c-485845c94a95',
                'url' => 'http://localhost:4400/contact.html',
                'normalized_url' => 'http://localhost:4400/contact.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Contact',
                'meta_description' => NULL,
            'clean_text' => 'Get in Touch Have questions? Our dummy support team is waiting (to not exist). Full Name Email Address Your Message Send Message',
                'content_hash' => 'f86845f4a17a36ceaeabe7b348790259c0f83625a7c9756f66ec99e14b6db70d',
                'word_count' => 22,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:17:03',
                'updated_at' => '2026-03-13 22:17:03',
            ),
            9 => 
            array (
                'id' => '019ce94f-6dad-719f-b3d7-417f2d572107',
                'crawl_job_id' => '019ce94f-6857-73ea-bd80-e2ce9ded4bff',
                'url' => 'http://localhost:4500/about.html',
                'normalized_url' => 'http://localhost:4500/about.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | About Us',
                'meta_description' => NULL,
                'clean_text' => 'About Our Mission Beyond the filler text, we aim to provide a canvas for your imagination. SleekDummy was founded on the principle that even dummy websites deserve to look stunning. We don\'t just provide "Lorem Ipsum"; we provide an experience. Our team of artificial intelligences worked tirelessly to ensure this pinker-than-average aesthetic meets the highest standards of the modern web. Every gradient is calculated, every blur is intentional. The Vision To redefine what users expect from a placeholder project. The Value Simplicity meets sophistication in every line of code.',
                'content_hash' => '84ba0557c52cceed6a45e446622fe5ed6d7149f3fbb647d2542cef186e513e28',
                'word_count' => 89,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:27:02',
                'updated_at' => '2026-03-13 22:27:02',
            ),
            10 => 
            array (
                'id' => '019ce94f-6dc0-7357-a978-6628dd0c0e42',
                'crawl_job_id' => '019ce94f-6857-73ea-bd80-e2ce9ded4bff',
                'url' => 'http://localhost:4500/contact.html',
                'normalized_url' => 'http://localhost:4500/contact.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Contact',
                'meta_description' => NULL,
            'clean_text' => 'Get in Touch Have questions? Our dummy support team is waiting (to not exist). Full Name Email Address Your Message Send Message',
                'content_hash' => 'f86845f4a17a36ceaeabe7b348790259c0f83625a7c9756f66ec99e14b6db70d',
                'word_count' => 22,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:27:02',
                'updated_at' => '2026-03-13 22:27:03',
            ),
            11 => 
            array (
                'id' => '019ce94f-6dd0-7104-a14e-5bfe62836865',
                'crawl_job_id' => '019ce94f-6857-73ea-bd80-e2ce9ded4bff',
                'url' => 'http://localhost:4500/terms.html',
                'normalized_url' => 'http://localhost:4500/terms.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Terms',
                'meta_description' => NULL,
                'clean_text' => 'Terms & Conditions The fine print that explains why nothing here is real. 1. Acceptance of Dummy Terms By accessing this website, you agree that you are viewing a demonstration project. No actual services, products, or real-world entities are represented here. 2. Use of Placeholder Data All images and text are for illustrative purposes only. Any resemblance to real life is purely coincidental and frankly, quite surprising. 3. Limitation of Liability We are not liable for any time spent admiring the sleek design or the inevitable disappointment when you realize the form doesn\'t actually send an email. 4. Intellectual Property The aesthetics of this dummy site are the property of the Antigravity AI Project. Feel free to be inspired by the CSS.',
                'content_hash' => 'f5cc25fe8849368a7cdea3977e38987a9a1a30d1fe13f8d25619782ac5282353',
                'word_count' => 117,
                'include_in_rag' => true,
                'created_at' => '2026-03-13 22:27:02',
                'updated_at' => '2026-03-13 22:27:03',
            ),
            12 => 
            array (
                'id' => '019ce9cd-0405-71a2-b1d9-ead09a03c085',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500',
                'normalized_url' => 'http://localhost:4500/',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 0,
                'title' => 'SleekDummy | Home',
                'meta_description' => NULL,
                'clean_text' => 'Experience the Future of Dummy Content. A premium demonstration of modern web aesthetics. Built with speed, precision, and an obsession for visual excellence. Discover Services About Us Lightning Fast Powered by Vite, our dummy pages load faster than you can blink. No bloat, just performance. Premium Design Coded with attention to every pixel. Micro-animations and glassmorphism included. Modern Stack Using the latest Vanilla JS and CSS techniques to ensure long-term stability.',
                'content_hash' => 'be8652a27c5b1adf5994476dee19b7de6d5904ba0757207e85681f08e6e93259',
                'word_count' => 71,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:13',
                'updated_at' => '2026-03-14 00:44:14',
            ),
            13 => 
            array (
                'id' => '019ce9de-d8b5-718e-9151-80636fa8eff3',
                'crawl_job_id' => '019ce9de-d8a4-7168-b821-57fb88b853ce',
                'url' => 'https://www.caterpillar.com',
                'normalized_url' => 'https://www.caterpillar.com/',
                'status' => 'failed',
                'http_status' => NULL,
                'depth' => 0,
                'title' => NULL,
                'meta_description' => NULL,
                'clean_text' => NULL,
                'content_hash' => NULL,
                'word_count' => 0,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 01:03:41',
                'updated_at' => '2026-03-14 01:03:59',
            ),
            14 => 
            array (
                'id' => '019ce9cd-0807-7340-a5d9-8fa8971bdb00',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/about.html',
                'normalized_url' => 'http://localhost:4500/about.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | About Us',
                'meta_description' => NULL,
                'clean_text' => 'About Our Mission Beyond the filler text, we aim to provide a canvas for your imagination. SleekDummy was founded on the principle that even dummy websites deserve to look stunning. We don\'t just provide "Lorem Ipsum"; we provide an experience. Our team of artificial intelligences worked tirelessly to ensure this pinker-than-average aesthetic meets the highest standards of the modern web. Every gradient is calculated, every blur is intentional. The Vision To redefine what users expect from a placeholder project. Return Home → The Value Simplicity meets sophistication in every line of code.',
                'content_hash' => 'ea71b57316dfb91ae96ee482976664f2e1f58618e018ecc2702a5b5b263bf6e5',
                'word_count' => 91,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:14',
            ),
            15 => 
            array (
                'id' => '019ce9cd-0815-71db-860c-051a93ef2d24',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/services.html',
                'normalized_url' => 'http://localhost:4500/services.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Services',
                'meta_description' => NULL,
            'clean_text' => 'Our Premium Services Tailored solutions for your hypothetical business needs. We offer everything you don\'t actually need. 🚀 Digital Strategy We craft complex Roadmaps for projects that will never launch. Strategy is our middle name (actually it\'s Dummy). 🎨 UI/UX Design Beautiful interfaces designed with the sole purpose of looking good in portfolios. User experience is a secondary concern. ⚙️ Cloud Arch Serverless, scalable, and entirely imaginary infrastructure. We build in the cloud, because that\'s where dreams are. 📊 Data Analytics Turning random numbers into beautiful charts. We find insights in data that doesn\'t even exist yet. Ready to start your journey? Check out our pricing tiers to find the perfect plan for your imaginary budget. View Pricing',
                'content_hash' => '5524e8f42f5b4e09c550256a4e2122bf2ba80c231e2693588043dc0d4c8c885d',
                'word_count' => 115,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:14',
            ),
            16 => 
            array (
                'id' => '019ce9cd-084a-71b7-8faf-72645fb72459',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/faq.html',
                'normalized_url' => 'http://localhost:4500/faq.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | FAQ',
                'meta_description' => NULL,
            'clean_text' => 'Frequently Asked Questions Everything you wanted to know about SleekDummy, answered by our hypothetical experts. What is SleekDummy exactly? + SleekDummy is a high-end demonstration project designed to showcase premium web aesthetics using vanilla technologies like Vite, TypeScript, and CSS. Are the services real? + No, all services, names, and content on this site are purely for demonstration purposes. We don\'t actually build imaginary cloud architectures (yet). Can I use this CSS for my own project? + Absolutely! The goal of this project is to inspire better design in dummy and placeholder websites. Feel free to inspect and learn. Why port 4500? + Because it\'s a nice, round number that doesn\'t conflict with most default development environments. Also, it looks professional in the address bar.',
                'content_hash' => '9723a88956a879c2a3757cdc1e1952476bf57454701408456a2d444bef0c9817',
                'word_count' => 120,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:15',
            ),
            17 => 
            array (
                'id' => '019ce9cd-0823-7360-9449-73428ce4c550',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/pricing.html',
                'normalized_url' => 'http://localhost:4500/pricing.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Pricing',
                'meta_description' => NULL,
            'clean_text' => 'Simple, Transparent Pricing Choose the plan that best fits your hypothetical scale. No credit card required (because we can\'t process it). Starter $0/mo Perfect for exploring the dummy ecosystem. 3 Placeholder Projects Basic CSS Support Community Forum Access Weekly Newsletters Get Started POPULAR Professional $49/mo For serious dummy project developers. Unlimited Dummy Sites Premium Animations 24/7 Bot Support Advanced Analytics Choose Plan Enterprise $Custom Tailored for massive dummy corporations. Custom Design Systems Dedicated Account Manager SLA Guarantees On-premise Deployment Contact Sales',
                'content_hash' => 'b54951540a91b0068856a6bd2b360a7696bd1c735da0f82b90970a356ef71d2f',
                'word_count' => 79,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:14',
            ),
            18 => 
            array (
                'id' => '019ce9cd-083c-73d9-bc06-e2a0f1052111',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/blog.html',
                'normalized_url' => 'http://localhost:4500/blog.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Blog',
                'meta_description' => NULL,
            'clean_text' => 'Insights & Dummy Thoughts Deep dives into the world of placeholder text and conceptual design. Read our latest (entirely fictional) articles. 📑 March 14, 2026 The Evolution of "Lorem Ipsum" in Modern UI How dummy text shaped the way we think about spacing, typography, and visual heirarchy in the digital age. Read More → 🎨 March 10, 2026 Glassmorphism: More Than Just a Blur? Analyzing why transparency and depth continue to dominate premium design systems globally. Read More → ⚡ March 05, 2026 Why Vite is the King of Developer Experience A look into the hot-module replacement and build speeds that make creating dummy sites a joy. Read More →',
                'content_hash' => '1f8f108ec0ccb807a230711d6e1ee2926308c445076083800f0ba1db12866ba2',
                'word_count' => 97,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:15',
            ),
            19 => 
            array (
                'id' => '019ce9cd-0856-7372-b68c-896432c9323e',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/team.html',
                'normalized_url' => 'http://localhost:4500/team.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Team',
                'meta_description' => NULL,
                'clean_text' => 'Meet the Dummy Team The creative minds behind the sleekest placeholders on the web. A group of talented individuals who don\'t actually work here. 👩‍💻 Alex Rivera Lead Architect Alex ensures every line of dummy code is perfectly aligned with our non-existent goals. 👨‍🎨 Jordan Smith Design Director The visionary responsible for our signature glassmorphic aesthetic and vibrant gradients. 👩‍💼 Sam Taylor Head of Product Sam manages our roadmap of imaginary features with unmatched hypothetical precision. 👨‍💻 Casey Lee Senior Developer Master of Vite and TypeScript. Casey can build a 10-page website in record-breaking dummy time.',
                'content_hash' => 'f6a89b21fd458d2fb27ac36c4fab836784cc0238e173d7cfa3e2e68dc83bd13d',
                'word_count' => 92,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:15',
            ),
            20 => 
            array (
                'id' => '019ce9cd-086e-71ca-bff6-5f442149f769',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/careers.html',
                'normalized_url' => 'http://localhost:4500/careers.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Careers',
                'meta_description' => NULL,
            'clean_text' => 'Join Our Dummy Team Help us build the most beautiful non-existent products in the world. We offer great (theoretical) benefits. Frontend Engineer (Vanilla JS) 📍 Remote / Imaginary Full-time Apply Now Visual Identity Designer 📍 Gradient City Full-time Apply Now Hypothetical Data Scientist 📍 The Cloud Contract Apply Now Don\'t see a role that fits? Send us an open application!',
                'content_hash' => '2b1caaf5fbbc25119d43fcf5d82aaaf01e46b55ce666a1148d53f43686962e7b',
                'word_count' => 56,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:15',
            ),
            21 => 
            array (
                'id' => '019ce9cd-087b-72b1-b587-099b7b20451e',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/contact.html',
                'normalized_url' => 'http://localhost:4500/contact.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Contact',
                'meta_description' => NULL,
            'clean_text' => 'Get in Touch Have questions? Our dummy support team is waiting (to not exist). Full Name Email Address Your Message Send Message',
                'content_hash' => 'f86845f4a17a36ceaeabe7b348790259c0f83625a7c9756f66ec99e14b6db70d',
                'word_count' => 22,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:16',
            ),
            22 => 
            array (
                'id' => '019ce9cd-0887-7357-834f-b76ecb61fc3d',
                'crawl_job_id' => '019ce9cd-03f8-71c7-9117-efddaee80afb',
                'url' => 'http://localhost:4500/terms.html',
                'normalized_url' => 'http://localhost:4500/terms.html',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 1,
                'title' => 'SleekDummy | Terms',
                'meta_description' => NULL,
                'clean_text' => 'Terms & Conditions The fine print that explains why nothing here is real. 1. Acceptance of Dummy Terms By accessing this website, you agree that you are viewing a demonstration project. No actual services, products, or real-world entities are represented here. 2. Use of Placeholder Data All images and text are for illustrative purposes only. Any resemblance to real life is purely coincidental and frankly, quite surprising. 3. Limitation of Liability We are not liable for any time spent admiring the sleek design or the inevitable disappointment when you realize the form doesn\'t actually send an email. 4. Intellectual Property The aesthetics of this dummy site are the property of the Antigravity AI Project. Feel free to be inspired by the CSS.',
                'content_hash' => 'f5cc25fe8849368a7cdea3977e38987a9a1a30d1fe13f8d25619782ac5282353',
                'word_count' => 117,
                'include_in_rag' => true,
                'created_at' => '2026-03-14 00:44:14',
                'updated_at' => '2026-03-14 00:44:16',
            ),
            23 => 
            array (
                'id' => '019ce94f-6869-718b-8147-46e36d2330f7',
                'crawl_job_id' => '019ce94f-6857-73ea-bd80-e2ce9ded4bff',
                'url' => 'http://localhost:4500',
                'normalized_url' => 'http://localhost:4500/',
                'status' => 'processed',
                'http_status' => 200,
                'depth' => 0,
                'title' => 'SleekDummy | Home',
                'meta_description' => NULL,
                'clean_text' => 'Experience the Future of Dummy Content. A premium demonstration of modern web aesthetics. Built with speed, precision, and an obsession for visual excellence. Discover More Get in Touch Lightning Fast Powered by Vite, our dummy pages load faster than you can blink. No bloat, just performance. Premium Design Coded with attention to every pixel. Micro-animations and glassmorphism included. Modern Stack Using the latest Vanilla JS and CSS techniques to ensure long-term stability.',
                'content_hash' => 'b03b56183682684dadf644de7b01942123299b759c9646da944cad61e5462fa6',
                'word_count' => 72,
                'include_in_rag' => false,
                'created_at' => '2026-03-13 22:27:01',
                'updated_at' => '2026-04-13 11:10:56',
            ),
        ));
        
        
    }
}