<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 4,
                'name' => 'Admin User',
                'email' => 'admin@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lS0zoKlFw/LnH3DUIWtp5O9msoAXoIxjR2FyB/.NLYfcdjvyeas..',
                'remember_token' => NULL,
                'created_at' => '2026-02-04 11:56:43',
                'updated_at' => '2026-02-04 12:37:20',
                'dealer_code' => 'GBANX0Z2',
                'company_name' => 'Admin Company',
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'avatars/RZZJqFs1pSd8BzTCkMWCIZnb70lmT93EwYvZRqCu.jpg',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => NULL,
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            1 => 
            array (
                'id' => 10,
                'name' => 'Test User',
                'email' => 'test@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$rKrqEvcyA5WWW7uoY9yXLue//yo4RZ6zGS8ZZ1yNphfIoeFOGziVe',
                'remember_token' => NULL,
                'created_at' => '2026-02-28 03:56:00',
                'updated_at' => '2026-02-28 03:56:00',
                'dealer_code' => 'PTD6GGSM',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => NULL,
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019ca263-939a-710a-9654-18b61f121850',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Brian Coxx',
                'email' => 'hakim.abdul.tech@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$5mdY/blLwiIJUf1k1TeH6etQJrv.GCiRZdPb2ChWMG275edqiaatS',
                'remember_token' => NULL,
                'created_at' => '2026-02-04 10:39:00',
                'updated_at' => '2026-05-08 16:03:26',
                'dealer_code' => 'YQN91C8U',
                'company_name' => 'Jojo Autos',
            'phone' => '+1 (555) 009-7993',
                'blocked_at' => NULL,
                'avatar' => 'avatars/qn3PcvLCkGAtkTlX16NfhE22hCrtHp9oQBXp64LG.jpg',
                'bio' => NULL,
                'banner_image' => 'banners/l7omlVUMlZRpxqoVFuqUBdAP7kS5QA66nhjDczRA.jpg',
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c6dae-bcb7-7388-a2c0-f465f5daf777',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            3 => 
            array (
                'id' => 18,
                'name' => 'Fatr Mossad',
                'email' => 'test.member.02@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$E3QtvTodLjY8Vzw94kVfke3FsE6AxkgzWeO95RHf/F6qR53Tuqxxy',
                'remember_token' => NULL,
                'created_at' => '2026-05-10 02:36:12',
                'updated_at' => '2026-05-10 02:36:12',
                'dealer_code' => 'EXVTMXPA',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'avatars/O0M19eJmLkYYE1YgRuMUwTXYk9wv51ocqCxHDk1w.png',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => NULL,
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            4 => 
            array (
                'id' => 19,
                'name' => 'Francine Robertson',
                'email' => 'test.member.03@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$m7he6Y5.Y5GKyfLlw.7rWOCiV6w1bxjqvASagESRVnKyMNJahXVR.',
                'remember_token' => NULL,
                'created_at' => '2026-05-10 02:38:23',
                'updated_at' => '2026-05-10 02:38:23',
                'dealer_code' => 'I0JNXZ8I',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'avatars/XF2MBJcsCoa6TfpFBHcFVKgb5BGutZqIGy1QRCQO.png',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => NULL,
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            5 => 
            array (
                'id' => 17,
                'name' => 'Fausty Nogur',
                'email' => 'test.member.01@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$0l6ePv4s5JSmmIlcEWdAyu3xqMFRn3BnNrKdyqWKI6g.WBDwiXSqm',
                'remember_token' => 'ugE6eL5dahii4PDdYBFfPbtiI0YNF6win1FlM2OZrsiHoGwB3gNmDmdwuKrH',
                'created_at' => '2026-05-10 02:30:39',
                'updated_at' => '2026-05-10 15:00:25',
                'dealer_code' => 'OBJKBNSS',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'avatars/Drd6rStDfodszTO5qud1HRIh0TbSqWlv9XXj1yH5.jpg',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c6dae-bcb7-7388-a2c0-f465f5daf777',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            6 => 
            array (
                'id' => 5,
                'name' => 'Jiji Jones',
                'email' => 'clerk@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Nbcy6qKA1B5Tao9syeJNB.e5Zc1kPfLLtH2GhxA1tnrvTM9Rdkjn6',
                'remember_token' => NULL,
                'created_at' => '2026-02-17 23:52:52',
                'updated_at' => '2026-02-17 23:57:55',
                'dealer_code' => 'AU4YGELQ',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => NULL,
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c6db7-c933-73af-8b20-abf5de5cc84a',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            7 => 
            array (
                'id' => 6,
                'name' => 'Test Google User',
                'email' => 'test_google_699637da64084@example.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-18 22:06:18',
                'updated_at' => '2026-02-18 22:06:18',
                'dealer_code' => 'ZXLAWDFT',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'https://example.com/avatar.jpg',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c72ca-2d80-73fe-a06c-bf6e0437e315',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            8 => 
            array (
                'id' => 7,
                'name' => 'Test Google User',
                'email' => 'test_google_699638778394a@example.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-18 22:08:55',
                'updated_at' => '2026-02-18 22:08:55',
                'dealer_code' => 'EN5LULI7',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'https://example.com/avatar.jpg',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c72cc-934e-7363-82e0-fd709fc7ea51',
                'google_id' => 'google_6996387783947',
                'is_super_admin' => false,
            ),
            9 => 
            array (
                'id' => 9,
                'name' => 'TechONE',
                'email' => 'techoneit.channel@gmail.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-18 23:16:56',
                'updated_at' => '2026-02-18 23:16:57',
                'dealer_code' => 'RTQ1CUQH',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'https://lh3.googleusercontent.com/a/ACg8ocIH99TPqwAIBD2Exm0n1zA2YuDT7BWZTsW3rBD_p_dIYToQlzY=s96-c',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c730a-da51-708c-96a5-b45e96cd9166',
                'google_id' => '105639941205990464001',
                'is_super_admin' => false,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Super Admin',
                'email' => 'super@admin.local',
                'email_verified_at' => NULL,
                'password' => '$2y$12$EUkV/giQT4OlogI5DuIIFu/cEglRnXidZGa/F0TFwfw8zruJq2WsS',
                'remember_token' => 'XrlAImQ85EMIgpjF4HN5SZf02KfyPcpVVimCLZzClUGJ6BaI9Or7XVuAOCGA',
                'created_at' => '2026-04-29 10:55:25',
                'updated_at' => '2026-04-29 23:41:03',
                'dealer_code' => 'QAPCV1OF',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => NULL,
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019dd9a8-e608-7354-b798-1525a1cf4e10',
                'google_id' => NULL,
                'is_super_admin' => true,
            ),
            11 => 
            array (
                'id' => 1,
                'name' => 'Hakim Abdul',
                'email' => 'abdulhakimaben@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Fjyylq1DK1FxlvM45lT.cu/1TYjzHqsItbc64uXKPhTRmxFLnVkfe',
                'remember_token' => 'Wu7t8DFPWHIyqg0cEhvIbiGdy5ldhseryF8lh8v9gQJ6wskdHCUdVC3bfwza',
                'created_at' => '2026-01-22 20:29:21',
                'updated_at' => '2026-05-07 13:06:37',
                'dealer_code' => NULL,
                'company_name' => 'Auto',
                'phone' => '+233593821578',
                'blocked_at' => NULL,
                'avatar' => 'avatars/cQRar4SK8rCwpesGldrIpNnIyrqYlPK9cemgAh4p.jpg',
                'bio' => 'HI end',
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => '[]',
                'years_in_business' => 8,
                'is_public_profile' => true,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c6dae-bcb7-7388-a2c0-f465f5daf777',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            12 => 
            array (
                'id' => 12,
                'name' => 'Member 01',
                'email' => 'member1@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$hsqqqskeULtwJ8p/mRxx5eZmrPtDGsEsXTzCI6Ew08Ec8aDFGHt1m',
                'remember_token' => NULL,
                'created_at' => '2026-05-04 23:48:26',
                'updated_at' => '2026-05-04 23:48:26',
                'dealer_code' => 'FE4VDOCJ',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => NULL,
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => NULL,
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            13 => 
            array (
                'id' => 13,
                'name' => 'Member 02',
                'email' => 'member2@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$TQDW7K8K8w7988hImuRkteYoaA0Jx.HOLAdzMdZAmBARqLCIQgmce',
                'remember_token' => NULL,
                'created_at' => '2026-05-04 23:49:28',
                'updated_at' => '2026-05-04 23:49:28',
                'dealer_code' => 'AT73LU9V',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => NULL,
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => NULL,
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Member 02',
                'email' => 'member02@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$dmU4vieNXoEZ1PEbA..iLOvu09WdSafGITrrPYVvcLQLf.4Q7nPnO',
                'remember_token' => NULL,
                'created_at' => '2026-05-05 00:07:53',
                'updated_at' => '2026-05-05 00:24:13',
                'dealer_code' => 'EM8LEJNX',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => NULL,
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c6dbb-d032-724b-863a-a92b1a3016da',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
            15 => 
            array (
                'id' => 14,
                'name' => 'Member 01',
                'email' => 'member01@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$HHhR62y05X3UXd0L9rp5vOAovhHJ/BOVJ1tlC3pfOfH3cQFr.IW2S',
                'remember_token' => NULL,
                'created_at' => '2026-05-05 00:05:00',
                'updated_at' => '2026-05-05 02:04:37',
                'dealer_code' => 'X7H5T6AM',
                'company_name' => NULL,
                'phone' => NULL,
                'blocked_at' => NULL,
                'avatar' => 'avatars/CuMVzet2upWYJyoOyxKVOAiu7n8Xlrd5n7pQHYs5.jpg',
                'bio' => NULL,
                'banner_image' => NULL,
                'location_city' => NULL,
                'location_country' => NULL,
                'specialties' => NULL,
                'years_in_business' => NULL,
                'is_public_profile' => false,
                'social_links' => NULL,
                'last_active_at' => NULL,
                'current_tenant_id' => '019c6dbb-d032-724b-863a-a92b1a3016da',
                'google_id' => NULL,
                'is_super_admin' => false,
            ),
        ));
        
        
    }
}